apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflowy
  namespace: appflowy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appflowy
  template:
    metadata:
      labels:
        app: appflowy
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: appflowy
          image: ghcr.io/jovanmontfort/appflowy-web:latest  # ← CHANGED TO YOUR IMAGE
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: appflowy-secret
                  key: database-url
            - name: RUST_LOG
              value: "info"
            - name: PORT
              value: "80"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: appflowy-data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: appflowy-data
          persistentVolumeClaim:
            claimName: appflowy-data-pvc