apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appflowy-data-pvc
  namespace: appflowy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi  # SQLite databases are small, 10GB is plenty
  storageClassName: scw-bssd  # Adjust based on your cluster