apiVersion: v1
kind: Namespace
metadata:
  name: mailcow
---
# PostgreSQL PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: mailcow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: scw-bssd  # Scaleway Block SSD Storage
---
# Mail data PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailcow-data
  namespace: mailcow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: scw-bssd