apiVersion: v1
kind: Service
metadata:
  name: mailcow-smtp
  namespace: mailcow
spec:
  type: LoadBalancer
  ports:
    - name: smtp
      port: 25
      targetPort: 25
    - name: submission
      port: 587
      targetPort: 587
    - name: smtps
      port: 465
      targetPort: 465
  selector:
    app: mailcow
---
apiVersion: v1
kind: Service
metadata:
  name: mailcow-imap
  namespace: mailcow
spec:
  type: LoadBalancer
  ports:
    - name: imaps
      port: 993
      targetPort: 993
    - name: pop3s
      port: 995
      targetPort: 995
  selector:
    app: mailcow
---
apiVersion: v1
kind: Service
metadata:
  name: mailcow-web
  namespace: mailcow
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: mailcow