apiVersion: v1
kind: Service
metadata:
  name: mailu-front
  namespace: mailcow
spec:
  type: LoadBalancer
  ports:
    - name: smtp
      port: 25
      targetPort: 25
      protocol: TCP
    - name: submission
      port: 587
      targetPort: 587
      protocol: TCP
    - name: smtps
      port: 465
      targetPort: 465
      protocol: TCP
    - name: imaps
      port: 993
      targetPort: 993
      protocol: TCP
    - name: pop3s
      port: 995
      targetPort: 995
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: mailu-front
---
apiVersion: v1
kind: Service
metadata:
  name: mailu-admin
  namespace: mailcow
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mailu-admin
---
apiVersion: v1
kind: Service
metadata:
  name: mailu-smtp
  namespace: mailcow
spec:
  ports:
    - port: 25
      targetPort: 25
    - port: 587
      targetPort: 587
    - port: 465
      targetPort: 465
  selector:
    app: mailu-smtp
---
apiVersion: v1
kind: Service
metadata:
  name: mailu-imap
  namespace: mailcow
spec:
  ports:
    - port: 993
      targetPort: 993
    - port: 995
      targetPort: 995
    - port: 143
      targetPort: 143
  selector:
    app: mailu-imap