apiVersion: v1
kind: Secret
metadata:
  name: appflowy-db-secret
  namespace: appflowy
type: Opaque
data:
  # Encode your values in base64
  database-url: <your-base64-encoded-connection-string> # e.g., postgresql://user:password@host:5432/dbname